import os
import sqlite3

# PostgreSQL is used on Render when DATABASE_URL is present.
# SQLite is kept as a local-development fallback.
DATABASE = "shop.db"
DATABASE_URL = os.getenv("DATABASE_URL")


class DatabaseConnection:
    """Small compatibility wrapper so the same app works with SQLite and PostgreSQL."""

    def __init__(self, connection, is_postgres=False):
        self._connection = connection
        self.is_postgres = is_postgres

    def execute(self, sql, params=None):
        # The app uses PostgreSQL-style %s placeholders.
        # SQLite uses ?, so translate only for local SQLite mode.
        if not self.is_postgres:
            sql = sql.replace("%s", "?")

        if params is None:
            return self._connection.execute(sql)

        return self._connection.execute(sql, params)

    def commit(self):
        return self._connection.commit()

    def rollback(self):
        return self._connection.rollback()

    def close(self):
        return self._connection.close()



def get_db_connection():
    """
    Return a database connection.

    Render:
        PostgreSQL is used when DATABASE_URL is configured.

    Local computer:
        SQLite shop.db is used when DATABASE_URL is not configured.
    """

    if DATABASE_URL:
        try:
            import psycopg
            from psycopg.rows import dict_row

            connection = psycopg.connect(
                DATABASE_URL,
                row_factory=dict_row
            )

            return DatabaseConnection(
                connection,
                is_postgres=True
            )

        except ImportError as error:
            raise RuntimeError(
                'PostgreSQL is configured through DATABASE_URL, but the '
                '"psycopg" package is not installed. Add '
                'psycopg[binary] to requirements.txt.'
            ) from error

    connection = sqlite3.connect(DATABASE)
    connection.row_factory = sqlite3.Row

    return DatabaseConnection(
        connection,
        is_postgres=False
    )



def create_tables():
    """Create all application tables and required columns."""

    connection = get_db_connection()

    try:
        if connection.is_postgres:
            create_tables_postgres(connection)
        else:
            create_tables_sqlite(connection)

        connection.commit()

    finally:
        connection.close()



def create_tables_postgres(connection):
    """Create the PostgreSQL schema used by Render."""

    connection.execute("""
        CREATE TABLE IF NOT EXISTS products (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            price DOUBLE PRECISION NOT NULL,
            category TEXT NOT NULL,
            image TEXT,
            description TEXT,
            stock INTEGER DEFAULT 0,
            active INTEGER DEFAULT 1
        )
    """)

    connection.execute("""
        CREATE TABLE IF NOT EXISTS orders (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            customer_name TEXT NOT NULL,
            mobile TEXT NOT NULL,
            address TEXT NOT NULL,
            pincode TEXT NOT NULL,
            total DOUBLE PRECISION NOT NULL,
            status TEXT DEFAULT 'Order Placed',
            payment_method TEXT DEFAULT 'COD',
            payment_status TEXT DEFAULT 'Pending',
            order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)

    connection.execute("""
        CREATE TABLE IF NOT EXISTS order_items (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            order_id INTEGER NOT NULL,
            product_id INTEGER NOT NULL,
            product_name TEXT NOT NULL,
            price DOUBLE PRECISION NOT NULL,
            quantity INTEGER NOT NULL,
            subtotal DOUBLE PRECISION NOT NULL,
            FOREIGN KEY (order_id) REFERENCES orders(id),
            FOREIGN KEY (product_id) REFERENCES products(id)
        )
    """)

    connection.execute("""
        CREATE TABLE IF NOT EXISTS notifications (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            order_id INTEGER NOT NULL,
            customer_name TEXT NOT NULL,
            mobile TEXT NOT NULL,
            message TEXT NOT NULL,
            notification_type TEXT DEFAULT 'Order',
            is_read INTEGER DEFAULT 0,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (order_id) REFERENCES orders(id)
        )
    """)

    # Safe migrations for a database that may already exist.
    connection.execute("""
        ALTER TABLE products
        ADD COLUMN IF NOT EXISTS active INTEGER DEFAULT 1
    """)

    connection.execute("""
        ALTER TABLE orders
        ADD COLUMN IF NOT EXISTS payment_method TEXT DEFAULT 'COD'
    """)

    connection.execute("""
        ALTER TABLE orders
        ADD COLUMN IF NOT EXISTS payment_status TEXT DEFAULT 'Pending'
    """)



def create_tables_sqlite(connection):
    """Create the SQLite schema used for local development."""

    connection.execute("""
        CREATE TABLE IF NOT EXISTS products (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            price REAL NOT NULL,
            category TEXT NOT NULL,
            image TEXT,
            description TEXT,
            stock INTEGER DEFAULT 0,
            active INTEGER DEFAULT 1
        )
    """)

    connection.execute("""
        CREATE TABLE IF NOT EXISTS orders (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            customer_name TEXT NOT NULL,
            mobile TEXT NOT NULL,
            address TEXT NOT NULL,
            pincode TEXT NOT NULL,
            total REAL NOT NULL,
            status TEXT DEFAULT 'Order Placed',
            payment_method TEXT DEFAULT 'COD',
            payment_status TEXT DEFAULT 'Pending',
            order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)

    connection.execute("""
        CREATE TABLE IF NOT EXISTS order_items (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            order_id INTEGER NOT NULL,
            product_id INTEGER NOT NULL,
            product_name TEXT NOT NULL,
            price REAL NOT NULL,
            quantity INTEGER NOT NULL,
            subtotal REAL NOT NULL,
            FOREIGN KEY (order_id) REFERENCES orders(id),
            FOREIGN KEY (product_id) REFERENCES products(id)
        )
    """)

    connection.execute("""
        CREATE TABLE IF NOT EXISTS notifications (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            order_id INTEGER NOT NULL,
            customer_name TEXT NOT NULL,
            mobile TEXT NOT NULL,
            message TEXT NOT NULL,
            notification_type TEXT DEFAULT 'Order',
            is_read INTEGER DEFAULT 0,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (order_id) REFERENCES orders(id)
        )
    """)

    # Migrations for an older local SQLite database.
    columns = connection.execute("""
        PRAGMA table_info(products)
    """).fetchall()

    column_names = [column["name"] for column in columns]

    if "active" not in column_names:
        connection.execute("""
            ALTER TABLE products
            ADD COLUMN active INTEGER DEFAULT 1
        """)

    columns = connection.execute("""
        PRAGMA table_info(orders)
    """).fetchall()

    column_names = [column["name"] for column in columns]

    if "payment_method" not in column_names:
        connection.execute("""
            ALTER TABLE orders
            ADD COLUMN payment_method TEXT DEFAULT 'COD'
        """)

    if "payment_status" not in column_names:
        connection.execute("""
            ALTER TABLE orders
            ADD COLUMN payment_status TEXT DEFAULT 'Pending'
        """)


if __name__ == "__main__":
    create_tables()

    if DATABASE_URL:
        print("PostgreSQL database and tables created successfully!")
    else:
        print("SQLite database and tables created successfully!")
